### ISSUE TITLE
Receiving error on Windows 10 machine for conda

### ISSUE THREAD

**Issue by RYucel** [mave5/podalize#1]
I tried to implement it on a windows 10 machine but no success. I received following error on creating env 
`conda env create -f environment.yml`
as 
'Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 

Is there any way to fix this? would like to test this good work

**Comment by mave5** [comment]
@RYucel Yes, it returns that error message on windows machines. 

The only solution that I can recommend for windows machines is to manually install the packages as needed. Staring with Pyannote then Whisper, then the rest.

1- create a conda env  
 
```
$ conda env create -n podalize python=3.9
```

2- activate env

3- install pyannoate.audio

4- install openai whisper

**Comment by naturian** [comment]
you have to add anaconda3 and anaconda3/env to PATH. But I'm still facing problems too..

**Comment by nusquama** [comment]
i have same problem on mac
ResolvePackageNotFound: 
- readline==8.2=h5eee18b_0
- pyrsistent==0.18.1=py39hb9d737c_1
- libgomp==11.2.0=h1234567_1
- ipykernel==5.5.5=py39hef51801_0
- lame==3.100=h7b6447c_0
- libuv==1.40.0=h7b6447c_0
- sqlite==3.39.3=h5082296_0
- ld_impl_linux-64==2.38=h1181459_1
- gnutls==3.6.15=he1e5248_0
- cudatoolkit==11.3.1=h2bc3f7f_2
- libidn2==2.3.2=h7f8727e_0
- torchvision==0.12.0=py39_cu113
- libwebp-base==1.2.4=h5eee18b_0
- lcms2==2.12=h3be6417_0
- ncurses==6.3=h5eee18b_3
- _openmp_mutex==5.1=1_gnu
- cffi==1.15.1=py39h74dc2b5_0
- torchaudio==0.11.0=py39_cu113
- bzip2==1.0.8=h7b6447c_0
- pyzmq==19.0.2=py39hb69f2a1_2
- brotlipy==0.7.0=py39h27cfd23_1003
- jpeg==9e=h7f8727e_0
- libstdcxx-ng==11.2.0=h1234567_1
- argon2-cffi-bindings==21.2.0=py39hb9d737c_2
- typing_extensions==4.3.0=py39h06a4308_0
- freetype==2.12.1=h4a9f257_0
- zstd==1.5.2=ha4553b6_0
- setuptools==63.4.1=py39h06a4308_0
- xz==5.2.6=h5eee18b_0
- zlib==1.2.13=h5eee18b_0
- libpng==1.6.37=hbc83047_0
- ffmpeg==4.3=hf484d3e_0
- gmp==6.2.1=h295c915_3
- nettle==3.7.3=hbbd107a_1
- idna==3.4=py39h06a4308_0
- openssl==1.1.1q=h7f8727e_0
- mkl_fft==1.3.1=py39hd3c417c_0
- libtasn1==4.16.0=h27cfd23_0
- ca-certificates==2022.9.24=ha878542_0
- zeromq==4.3.4=h9c3ff4c_1
- mkl_random==1.2.2=py39h51133e4_0
- pandoc==2.19.2=ha770c72_0
- numpy==1.23.3=py39h14f4228_0
- jupyter_core==4.11.1=py39hf3d152e_1
- cryptography==38.0.1=py39h9ce1e76_0
- libgcc-ng==11.2.0=h1234567_1
- pillow==9.2.0=py39hace64e9_1
- libffi==3.3=he6710b0_2
- tk==8.6.12=h1ccaba5_0
- pytorch==1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
- markupsafe==2.1.1=py39hb9d737c_1
- pysocks==1.7.1=py39h06a4308_0
- libunistring==0.9.10=h27cfd23_0
- requests==2.28.1=py39h06a4308_0
- lerc==3.0=h295c915_0
- urllib3==1.26.12=py39h06a4308_0
- pip==22.2.2=py39h06a4308_0
- python==3.9.13=haa1d7c7_2
- lz4-c==1.9.3=h295c915_1
- giflib==5.2.1=h7b6447c_0
- mkl-service==2.4.0=py39h7f8727e_0
- libtiff==4.4.0=hecacb30_0
- intel-openmp==2021.4.0=h06a4308_3561
- numpy-base==1.23.3=py39h31eccc5_0
- libiconv==1.16=h7f8727e_2
- libsodium==1.0.18=h36c2ea0_1
- mkl==2021.4.0=h06a4308_640
- openh264==2.1.1=h4ff587b_0
- libwebp==1.2.4=h11a3e52_0
- libdeflate==1.8=h7f8727e_5

**Comment by RZiane** [comment]
@nusquama @RYucel 
i solve this running before: 
conda env export -n podalize -f environment.yml --from-history
