### ISSUE TITLE
Request - Podcast URL to transcribe

### ISSUE THREAD

**Issue by carlosalosno** [mave5/podalize#3]
First of all I wanted to congratulate you for this excellent work and for sharing the project....

I was wondering if it would be too complicated (I am not a developer) to implement a method to get the audio files to transcribe from the URL of a podcast, in the same way that now you can do with youtube videos, but only with the audio and convert the audio (most can be in mp4 .m4a to mp3 at the compression that podalize needs to work).

It would be a really great tool for those of us who transcribe our podcasts.

**Comment by mave5** [comment]
@carlosalosno Good idea! I will try to add this feature in the next update.

**Comment by mave5** [comment]
added option for podcast url

**Comment by carlosalosno** [comment]
Thank you very much, this tool brings a lot of value. What would be the best way to update the local version I have of Podalize?

**Comment by carlosalosno** [comment]
I do a git pull as seems to update, but when i try to put the Podcast URL, my podcast is in Anchor, 

https://anchor.fm/s/6dd99ff0/podcast/play/61769304/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2022-11-6%2F3c902a9d-df0e-e1cd-eb23-c999bc4543d0.m4a

I got thsi error

FileNotFoundError: [Errno 2] No such file or directory: 'youtube-dl'
Traceback:

File "/home/charlie/anaconda3/envs/podalize/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 564, in _run_script
    exec(code, module.__dict__)
File "/home/charlie/podalize/podalize_app.py", line 30, in <module>
    subprocess.run([f"youtube-dl", f"{youtube_url}", f"-o{path2out}"])
File "/home/charlie/anaconda3/envs/podalize/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
File "/home/charlie/anaconda3/envs/podalize/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
File "/home/charlie/anaconda3/envs/podalize/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
