### ISSUE TITLE
Separete output of pyannote.audio and OpenAI Whisper

### ISSUE THREAD

**Issue by kunniva** [mave5/podalize#9]
Hello, 

Is it possible to separate the output of pyannote.audio and OpenAI Whisper?

I think being able to process pyannote.audio first, save the results, and later run OpenAI Whisper manually little by little on the segments generated with pyannote.audio can help to deal with very large podcasts.

Do you think it is possible to separate functionalities?

**Comment by mave5** [comment]
For larger mp3 files, you can change the upload size in the .file_uploader method of Streamlit.
I kept it at its default value. See page for details:
https://docs.streamlit.io/knowledge-base/deploy/increase-file-uploader-limit-streamlit-cloud
